---
# tasks file for ansible-role-tripleo-dovetail

- name: Install packages and dependencies
  sudo: true
  yum:
    name: "{{ item.name }}"
    state: "installed"
  with_items:
    - { name: "python-pip" }
    - { name: "python-devel" }
    - { name: "git" }
    - { name: "gcc" }
    - { name: "docker" }

- name: Git clone dovetail
  sudo: true
  git:
    repo: "{{ dovetail_url }}"
    dest: "{{ working_dir }}"
    clone: yes
    update: yes
    force: yes

- name: Install dovetail
  sudo: true
  pip:
    name: "{{ working_dir }}"
    extra_args: -e
