---
# tasks file for ansible-role-tripleo-dovetail

- name: Start docker service
  sudo: true
  systemd:
    name: docker
    state: started
    enabled: True

- name: Generate env file
  command: cp -rn /home/stack/overcloudrc /home/stack/dovetail_env

- name: Config OS_TENANT_NAME
  lineinfile:
    dest: /home/stack/dovetail_env
    regexp: "OS_TENANT_NAME="
    line: 'export OS_TENANT_NAME=admin'

- name: Config DOVETAIL_HOME
  lineinfile:
    dest: /home/stack/dovetail_env
    regexp: "DOVETAIL_HOME"
    line: 'export DOVETAIL_HOME={{ working_dir }}'
