---
# tasks file for ansible-role-tripleo-dovetail

- name: Start docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: True

- name: make sure pre_config dir exist
  become: true
  file:
    path: "{{ working_dir }}/pre_config"
    state: directory
    mode: 0755

- name: Generate env file
  become: true
  command: cp -rn /home/stack/overcloudrc {{ working_dir }}/pre_config/{{ env_file }}

- name: Config OS_TENANT_NAME
  become: true
  lineinfile:
    dest: "{{ working_dir }}/pre_config/{{ env_file }}"
    regexp: "OS_TENANT_NAME="
    line: 'export OS_TENANT_NAME=admin'

- name: Config DOVETAIL_HOME
  become: true
  lineinfile:
    dest: "{{ working_dir }}/pre_config/{{ env_file }}"
    regexp: "DOVETAIL_HOME"
    line: 'export DOVETAIL_HOME={{ working_dir }}'
