---
# tasks file for ansible-role-tripleo-dovetail

- name: Get undercloud IP address
  shell: "ip route get 1.1.1.1 | grep -oP 'src \\K\\S+'"
  register: undercloud_ip

- name: Run dovetail
  sudo: true
  shell: "/usr/bin/dovetail run -d {{ enable_debug }} -t {{ sut_type }} -i {{ undercloud_ip.stdout }} -f {{ functest_tag }} -y {{ yardstick_tag }} --testsuite {{ testsuite }} 2>&1"
  register: dovetail_result
