---
# tasks file for ansible-role-tripleo-dovetail

- name: Get undercloud IP address
  shell: ""
  register: undercloud_ip

- name: Run dovetail
  sudo: true
  shell: |
    "/usr/bin/dovetail run -d {{ enable_debug }} -t {{ sut_type }} -i {{ undercloud_ip.stdout }} --testsuite {{ testsuite }} 2>&1"
  register: dovetail_result
  ignore_errors: true
