---
- hosts: localhost
  tasks:
   - name: Copy public key
     command: cat ~/.ssh/id_rsa.pub
     register: undercloud_ssh_key

   - name: Append public key to authorized_key
     lineinfile:
       dest: ~/.ssh/authorized_keys
       line: '{{ undercloud_ssh_key.stdout }}'
       create: yes

#- name: Install epel repo
#  become: true
#  hosts: localhost
#  gather_facts: no
#  roles:
#    - geerlingguy.repo-epel
#  tags: install-epel

- name: Run dovetail
  hosts: localhost
  gather_facts: no
  roles:
    - ansible-role-tripleo-dovetail
